name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Change to your desired Node.js version
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build:parcel

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "Riddhiman Raguraman"
          git config user.email "raguramanriddhiman@gmail.com"
          git checkout --orphan gh-pages
          git add .
          git commit -m "GitHub Pages build $(date)"
          git push origin gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
    

