name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Change to your desired Node.js version
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build:parcel

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build # Adjust if your build output directory is different
 
